env:
  global:
    - secure: Dnk1a6H/paRtVJZTH8kncNNSD/Htv9dUVoKQyPZEkPNeWq1M6pZy0Bl4UTRXlem3aFPqqyReY/2VTsulfmVormjHuVFF9LdlZ6k8BNikRIBFNe8EqR9v6cAN6KKML/cKSDDzhajea1JXvTU8/pRz/Y4BFhNeBjoUbnppUSkcFVk=
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libarpack2-dev
  - curl https://static.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo build
  - cargo test
  - cargo doc
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
