env:
  global:
    - secure: eekSPkcDT6vC31bcboqcdM5csWX+cMqTsyNHBxK/uTwmJgeJUXyKZlA+LnSmxZED1R5pwWuh44tuHdSw/9rA/sTPKZyFp/utnKTeCekuHdFhCibjaRqwWDnkvx7JWU++I/02UY08Pwo87J/BAOjv2fO9q5+V4Z/BzrDLxehm+FE=
language: rust
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq libarpack2-dev
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
after_script:
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
