[package]

name = "arpack.rs"
version = "0.1.0-git"
authors = ["Jim Garrison <jim@garrison.cc>"]

[lib]

name = "arpack"
path = "src/lib.rs"

[dependencies.num]

git = "https://github.com/rust-lang/num.git"
